# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'

Options:
  # exlucde large generated files from cppcheck, takes way to long to run
  cppcheck-ignore-files:
  - 'src/lib/knowledgedb/linemetadata_data.cpp'
  - 'src/lib/knowledgedb/linemetadata.cpp'
  require-passing-tests-on: [ 'Linux', 'FreeBSD', 'Windows' ]
