# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'

Options:
  # exlucde large generated files from cppcheck, takes way to long to run
  cppcheck-arguments: '-i src/lib/knowledgedb/linemetadata_data.cpp -i src/lib/knowledgedb/linemetadata.cpp --enable=warning,style,performance'
