# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt5', 'FreeBSD/Qt5', 'Windows/Qt5', 'Android/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/ki18n': '@stable'

- 'on': ['Linux/Qt5']
  'require':
    'frameworks/networkmanager-qt': '@stable'

- 'on': ['Linux/Qt6', 'FreeBSD/Qt6', 'Windows/Qt6', 'Android/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'

- 'on': ['Linux/Qt6']
  'require':
    'frameworks/networkmanager-qt': '@latest-kf6'

Options:
  # exlucde large generated files from cppcheck, takes way to long to run
  cppcheck-ignore-files:
  - 'src/lib/knowledgedb/linemetadata_data.cpp'
  - 'src/lib/knowledgedb/linemetadata.cpp'
  require-passing-tests-on: [ 'Linux', 'FreeBSD', 'Windows' ]
  json-validate-ignore:
  - 'autotests/data/hafas/rem-I-JF-sbb-split-layout-train-formation-input.json'
  - 'autotests/data/hafas/query-location-response-sbb-broken-json.json'
  - 'autotests/data/navitia/journey-bss-path-no-instr-start-coord.json'
  - 'autotests/data/ivvass/journey-vrs-input.json'
  - 'autotests/data/ivvass/journey-long-distance-vrs-input.json'
  - 'autotests/data/onboard-journey/db-ice.in.json'
  - 'autotests/data/otp/de-stadtnavi-bike-parking-journey.in.json'
